release: python manage.py migrate
python manage.py runserver 0.0.0.0:$PORT

web: gunicorn mysite.wsgi:application --log-file - --log-level debug
python manage.py collectstatic --noinput
manage.py migrate